"""Removed unused columns

Revision ID: 68c88e874ecf
Revises: 330521989b80
Create Date: 2025-06-17 14:36:00.203943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c88e874ecf'
down_revision: Union[str, None] = '330521989b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_species', sa.Column('base_stats', sa.Integer(), nullable=True))
    op.drop_column('monster_species', 'base_hp')
    op.drop_column('monster_species', 'base_defense')
    op.drop_column('monster_species', 'base_attack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_species', sa.Column('base_attack', sa.INTEGER(), nullable=True))
    op.add_column('monster_species', sa.Column('base_defense', sa.INTEGER(), nullable=True))
    op.add_column('monster_species', sa.Column('base_hp', sa.INTEGER(), nullable=True))
    op.drop_column('monster_species', 'base_stats')
    # ### end Alembic commands ###
